name: Cron Job workflow
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  cron_job_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run Python script
        run: python hello.py
